### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by rtgtgth** [lwd-temp/sola-virus#1]
Hello, sir, is this the source code of the sola virus? I have always liked this virus very much. I really want to study its source code, even if you spend money to buy it.

**Comment by SunsetMkt** [comment]
I guess yes?

https://github.com/lwd-temp/sola-virus/blob/master/%E6%96%B0%E5%BB%BA%20%E6%96%87%E6%9C%AC%E6%96%87%E6%A1%A3.exe.virus is an example of virus executable.

The virus source is extracted alongside.
